### ISSUE TITLE
How to translate the pin definitions of Raspberry Pi? I want to change sides dc and rst.

### ISSUE THREAD

**Issue by todayjt** [adafruit/Adafruit_CircuitPython_RGB_Display#102]
How to translate the pin definitions of Raspberry Pi? I want to change sides dc and rst.But I don't know how to compare the pins of the raspberr pi of the board. For example, in the Raspberry Pi ZERO W, does GPIO6 correspond to D6 or what?

**Comment by ladyada** [comment]
correct!
https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/digital-i-o
