### ISSUE TITLE
Raspberry Pi B V1.2 white screen issue

### ISSUE THREAD

**Issue by jaykeerti** [adafruit/Adafruit_CircuitPython_RGB_Display#109]
I have attached an SPI  TFT display as per the following connection. all i get is a white screen nothing else. 
the code loop runs without errors.

 : [Display product Link](https://robu.in/product/2-8-inch-spi-touch-screen-module-tft-interface-240320/)

![Capture](https://user-images.githubusercontent.com/16056169/209801957-4d2fe675-1738-4350-be0a-c400c20abbe9.PNG)

**Comment by ladyada** [comment]
robu.in can help you with their products
