### ISSUE TITLE
Optional Type hint fails

### ISSUE THREAD

**Issue by eichblatt** [adafruit/Adafruit_CircuitPython_RGB_Display#112]
This line fails when I try importing this library.

https://github.com/adafruit/Adafruit_CircuitPython_RGB_Display/blob/6ca64553a5f3e4aa718b2ee7ac8e4a0c07a6019b/adafruit_rgb_display/st7735.py#L196

**Comment by FoamyGuy** [comment]
@eichblatt can you post the full error?

If possible can you also try the previous release (found here: https://github.com/adafruit/Adafruit_CircuitPython_RGB_Display/releases/tag/3.11.0 ) The library was just recently updated, it's possible we need another tweak on top to get that portion fixed.

**Comment by tekktrik** [comment]
My guess is it's failing because `Optional` is being given a module as an input instead of the `DigitalInOut` class, I can submit a fix and see if that fixes it.

**Comment by eichblatt** [comment]
Sorry for the terse post. By the time I identified the problem, I had already reverted to the old version that I knew worked. So I could not reproduce the error, or find it in my log.  But I wanted to make sure that you knew, and figured a terse message was better than no message. 

I will unpin the version, and update again. If it breaks, I will collect the error messages and post here. 

Thank you!!

**Comment by truongminhdien8330-web** [comment]
nostr@nakamotoinstitute.org https://example.org/Mở/Agribank7501205196575@satoshinakamoto.org

**Comment by truongminhdien8330-web** [comment]
https://nakamotoinstitute.org/
youtube.com/@nakamotoinstitute
Agribank7501205196575@nostenakamotoinstitute.org
db.cpp
FIRSTGFT
BOGO40
GOATBLIZ
COPIED!
bin/cli.sh
272,311
README.md/example.com/Page/FIRSTGFT.zip/B4R.exe/feed.xml/bitcoin (2) (1).pdf/URLCheck-3.4.1.apk/#5822091959.pgp/97395902/         bitcoin (2) (1).pdfAgribank7501205196575bitcoin (1).pdf#5822091959.html#5822091959.pgpB4R.exeFIRSTGFT.zip     @nostenakamotoinstitute.org/telegram.web+840819543643/telegram.web+840916363743/example.com/vnexpress.net/andrewgstanton.com/example.orrg/mở/nostr@nakamotoinstitute.org
