### ISSUE TITLE
Example names do not match repo name

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_RGB_Display#30]
The examples all start with `rgbdisplay_` and should begin with `rgb_display_`. Examples need to be renamed to match CircuitPython library standards.

The lines including this file name in the `docs/examples.rst` file must also be updated to reflect the name change, e.g.:
```
.. literalinclude:: ../examples/current_file_name.py
    :caption: examples/current_file_name.py
    :linenos:
```
would be updated to:
```
.. literalinclude:: ../examples/current_file_name_changed.py
    :caption: examples/current_file_name_changed.py
    :linenos:
```

**Comment by makermelissa** [comment]
Fixed by #31
