### ISSUE TITLE
Cookiecutter this!

### ISSUE THREAD

**Issue by tannewt** [adafruit/Adafruit_CircuitPython_RGB_Display#6]
We need to make sure all files from cookiecutter are here and that the README matches the template.

For instructions on cookiecutter see [here](https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/sharing-our-docs-on-readthedocs?view=all#cookie-cutter).

**Comment by tannewt** [comment]
@mrmcwethy would you mind doing this? Looks like its missing the code of conduct at least.

**Comment by mrmcwethy** [comment]
I will do this.

**Comment by mrmcwethy** [comment]
Pull request merged and release created.
