### ISSUE TITLE
Usage with displayio?

### ISSUE THREAD

**Issue by philippkeller** [adafruit/Adafruit_CircuitPython_RGB_Display#63]
I'm trying to use `adafruit-circuitpython-display-text` in combination with this repo.

I found the following code in [this video](https://www.youtube.com/watch?v=ULtfNxDvoyM)

```
import board
import displayio
from st7735r import ST7735R

spi = board.SPI()
cs = board.D11
dc = board.D10

displayio.release_displays()
display_bus = displayio.FourWire(spi, command=dc, chip_select=cs, reset=board.D9)

display = ST7735R(display_bus, width=128, height=160)
```

Is something like this possible? Or should I use [this repo](https://github.com/adafruit/Adafruit_CircuitPython_ST7735R) instead?

I tried using the code, but I can't import `displayio` and I have no idea what pip package provides `displayio`.

**Comment by ladyada** [comment]
yep use the other one, this is for linux/python use :)

**Comment by philippkeller** [comment]
@ladyada I want to use it on a raspberrypi, so it's linux. Also I have a ST7735S (waveshare 1.8inch). Should I still the other repo? That means I adapt it to use the ST7735S init sequence?

**Comment by ladyada** [comment]
oh for a Pi, yeah use this repo - but you cannot use displayio! we have not used ST7735S so not sure how to get it working.

**Comment by philippkeller** [comment]
for whoever stumbles upon this: As far as I understand the things are as following:

For the Raspberry PI the circuitpython modules have been "side ported" in [adafruit-blinka](https://github.com/adafruit/Adafruit_Blinka#introduction). However, this only includes a few modules (e.g. busio, board, etc.) but not digitalio.

For using digitalio you'd need to develop on circuitpython hardware (e.g. Adafruit devices).

**Comment by ladyada** [comment]
digitalio is supported. displayio is not

**Comment by philippkeller** [comment]
thanks for spotting the mistake, updated my comment

**Comment by caternuson** [comment]
There's an open issue for `displayio` in Blinka:
https://github.com/adafruit/Adafruit_Blinka/issues/109
