### ISSUE TITLE
'No module named displayio' error on raspberry pi zero

### ISSUE THREAD

**Issue by hyansuper** [adafruit/Adafruit_CircuitPython_RGB_Display#71]
Hi, Is Raspberry pi zero w with 1.14 inch st7789 LCD supported?
I pip installed adafruit-blinka and adafruit-circuitpython-rgb-display, but when I tried the rgb_display_simpletest.py example, I got 'No module named displayio' Error, and I can't pip install 
 adafruit-circuitpython-displayio

**Comment by ladyada** [comment]
please follow this guide :)
https://learn.adafruit.com/adafruit-1-14-240x135-color-tft-breakout/python-wiring-and-setup

**Comment by hyansuper** [comment]
Thank you!
displayio and terminalio is not needed for Raspberry pi

**Comment by baugusto** [comment]
Hi!! 
And how did you install displayio and terminalio on RaspberryPI? 

I couldn't figure out how to install

**Comment by makermelissa** [comment]
> Hi!! And how did you install displayio and terminalio on RaspberryPI?
> 
> I couldn't figure out how to install

It's a separate library. Instructions are on https://github.com/adafruit/Adafruit_Blinka_Displayio/releases. Learn guide for it is at https://learn.adafruit.com/running-pyportal-code-on-blinka-with-displayio. I recently released a major update, so the guide may need some updating as well, but should be enough to help you.
