### ISSUE TITLE
Inverted colors when using PITFT 2.8" TFT 320X240 + CAPACITIVE

### ISSUE THREAD

**Issue by tubededentifrice** [adafruit/Adafruit_CircuitPython_RGB_Display#77]
When using a PITFT 2.8" TFT 320X240 + CAPACITIVE ( https://www.adafruit.com/product/1983 ), colors are inverted.

```
disp.fill(color565(255, 0, 0))  # red => Fills the screen with blue (cyan)
disp.fill(color565(0, 0, 255))  # blue => Fills with Yellow
disp.fill(color565(0, 255, 0))  # green => Magenta
```

It's probably just and initialization issue, but I don't know enough to fix it myself (besides manually inverting colors).

The display is initialized with

```
disp = ili9341.ILI9341(
    spi,
    rotation=270,  # 2.2", 2.4", 2.8", 3.2" ILI9341
    cs=cs_pin,
    dc=dc_pin,
    rst=reset_pin,
    baudrate=BAUDRATE,
)
```
otherwise it's just the sample from https://github.com/adafruit/Adafruit_CircuitPython_RGB_Display#22-24-28-32-tft

When using the sample AnimatedGif the images look inverted as well.

Thanks.

**Comment by ladyada** [comment]
is this on a raspberry pi or...?

**Comment by tubededentifrice** [comment]
Yep, it's a Raspberry Pi 3B+, sorry forgetting mentioning it.

**Comment by ladyada** [comment]
make sure you've updated all your python libraries, we've made bug fixes recently

**Comment by tubededentifrice** [comment]
Gosh, this is a brand new install, and though everything was up to date already, but after upgrading everything the colors are now the way they should :)

Thanks you!

For future people hitting this issue, just do:

```
apt update && apt dist-upgrade
pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip3 install -U
```

**Comment by tubededentifrice** [comment]
In reality, I think I actually made it work because I accidentally mixed up 2 examples.
Here's what work (the provided sample still doesn't and shows, for example, green instead of blue):

```
import digitalio
import board

spi = board.SPI()
display = ili9341.ILI9341(
    spi,
    rotation=270,
    cs=digitalio.DigitalInOut(board.CE0),
    dc=digitalio.DigitalInOut(board.D25),
    rst=digitalio.DigitalInOut(board.D24),
    baudrate=64000000
)
```
