### ISSUE TITLE
FR: Backlight control

### ISSUE THREAD

**Issue by tubededentifrice** [adafruit/Adafruit_CircuitPython_RGB_Display#78]
Would it be feasible to provide backlight control through those interfaces?
I know it's just some PWM on a specific pin, but it would make things easier.

Thanks.

**Comment by makermelissa** [comment]
Hi, it probably wouldn't be feasible since this library is now primarily supported on Blinka and not all boards on Blinka have PWMOut available. If you are using a board running CircuitPython, it would make more sense to use displayio since that's already built-in.
