### ISSUE TITLE
/dev/spidev0.0 does not exist

### ISSUE THREAD

**Issue by dima72** [adafruit/Adafruit_CircuitPython_RGB_Display#86]
```
Traceback (most recent call last):
  File "rgb_display_minipitfttest.py", line 14, in <module>
    board.SPI(),
  File "/usr/local/lib/python3.7/dist-packages/board.py", line 186, in SPI
    return busio.SPI(SCLK, MOSI, MISO)
  File "/usr/local/lib/python3.7/dist-packages/busio.py", line 186, in __init__
    self._spi = _SPI(portId)
  File "/usr/local/lib/python3.7/dist-packages/adafruit_blinka/microcontroller/generic_linux/spi.py", line 22, in __init__
    self._spi = spi.SPI(device=(portid, 0))
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_PureIO/spi.py", line 165, in __init__
    raise IOError("{} does not exist".format(device))
OSError: /dev/spidev0.0 does not exist
```
running **rgb_display_minipitfttest.py** after installing **adafruit-circuitpython-rgb-display**, **spidev**, **ttf-dejavu**, **python3-numpy**

please help

**Comment by caternuson** [comment]
Make sure you've enabled SPI:
https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/installing-circuitpython-on-raspberry-pi#enable-i2c-and-spi-2993390-7

**Comment by dima72** [comment]
Thank you Nelson

can you suggest if I'm missing something else, looking auth the picture
![image](https://user-images.githubusercontent.com/4633233/94373159-900f0380-00d1-11eb-8768-0bdfd3666437.png)

thanks in advance,

**Comment by caternuson** [comment]
Looks like it's working in terms of hardware. Is your concern now the glitchy background?

**Comment by makermelissa** [comment]
Looks like you're running a 240x135 demo on a 240x240 display.

**Comment by dima72** [comment]
The problem is, even if I send 240x240 into constructor, the image comes as 240x135. Do I use right st7789.ST7789 constructor?

```
# Create the ST7789 display:
disp = st7789.ST7789(
    spi,
    cs=cs_pin,
    dc=dc_pin,
    rst=reset_pin,
    baudrate=BAUDRATE,
    width=240,
    height=240,
    x_offset=0, #53
    y_offset=10, #40
)

```

![image](https://user-images.githubusercontent.com/4633233/94435552-44a83400-0169-11eb-9bb0-de2e9a6eea9c.png)

**Comment by ladyada** [comment]
try tweaking the y offset!

**Comment by caternuson** [comment]
see here:
https://learn.adafruit.com/adafruit-mini-pitft-135x240-color-tft-add-on-for-raspberry-pi/python-stats#modifications-for-the-1-dot-3-display-3066993-6

**Comment by dima72** [comment]
cool. `y_offset=80` works fine.
thanks for your support!
