### ISSUE TITLE
Touch Support

### ISSUE THREAD

**Issue by justcallmekoko** [adafruit/Adafruit_CircuitPython_RGB_Display#87]
What would it take to add touch support to this library?

**Comment by ladyada** [comment]
we have some resistive/capacitive touchscreen drivers :)
https://github.com/adafruit?q=touch+circuitpython&type=&language=
touch screens are separate from the displays (always have been)

**Comment by justcallmekoko** [comment]
@ladyada Awesome I will have to take a look at those.
Do they happen to work with the XPT2046?

**Comment by ladyada** [comment]
i am not aware of a xpt2046 circuitpython library
