### ISSUE TITLE
Text is inverted

### ISSUE THREAD

**Issue by kevisoft** [adafruit/Adafruit_CircuitPython_RGB_Display#92]
Hello,

I've been messing with this library for a while now and when I import Image.Draw text it displays on my ST7789 screen but it comes out inverted. I tried messing with ST7789.py and noticed an option called "_INVON" and I thought maybe this had something to do with it?

**Comment by ladyada** [comment]
are you using an adafruit-made ST7789 screen?

**Comment by kevisoft** [comment]
> are you using an adafruit-made ST7789 screen?

Yes, in fact after some more tinkering I realized I was using the wrong driver. I realized my screen utilizes hx8537, but the text is still inverted. I am using this screen https://www.adafruit.com/product/2441

**Comment by ladyada** [comment]
ok! you can post in the adafruit tech support forums for code help. thanx!
